### ISSUE TITLE
fails with "unsupported shell"  when sh is dash

### ISSUE THREAD

**Issue by gaetano-guerriero** [se7entyse7en/pydockenv#52]
On my system `/bin/sh` is dash shell.

Test for shell compatibility at the start of `pydockenv` binary fails since the script is started with `/usr/bin/env sh`

**Comment by goodaleb-cloudbees** [comment]
On my system (Ubuntu 16.04), `/bin/sh` is *bash* shell, but I also get the same "unsupported shell".  Should be an easy fix by either editing the `pydockenv ` binary, or modifying one or more of my environment variables, but not certain of best fix; some guidance would be appreciated.

**Comment by se7entyse7en** [comment]
This is something that also affects integration tests on Travis. Currently, the easiest fix that you could try is the same that I used [here](https://github.com/se7entyse7en/pydockenv/blob/master/.travis.yml#L14). By replacing the shebang of the binary to whatever you need for your installation. So something like:
```
sed -i 's/#!\/usr\/bin\/env sh/#!\/bin\/bash/' $(which pydockenv)
```
should do the trick. I didn't have time to think about the best solution yet, but this is surely the issue that I'll prioritize.

**Comment by se7entyse7en** [comment]
An alternative temporary fix could be to have an alias such as:
```
alias pydockenv="bash pydockenv"
```

**Comment by gaetano-guerriero** [comment]
tried a fix here https://github.com/se7entyse7en/pydockenv/pull/55.
